Fix/uppsf 2800 clean test deps
Financial-Times/public-content-by-concept-api pull request #38
Opened 2021-12-08 12:46 UTC by epavlova

# Description

## What

- Update the integration test dependencies - `concepts-rw-neo4j`, `content-rw-neo4j` and `annotations-rw-neo4j` and thus removing the dependency `neo-utils-go`.
- Fix a new issue that appeared after running the migration tests on 4.3.6. The integration tests allowed negative value to be set as skip param in Neo query. Apparently, this is no longer allowed. In practice this shouldn't happen because of the parsing of the input params in the handler's code.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-2800

## Scope and particulars of this PR (Please tick all that apply)

- [X] Tech hygiene (dependency updating & other tech debt)
- [X] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-12-08 12:47 UTC, epavlova commented
This PR waits https://github.com/Financial-Times/content-rw-neo4j/pull/53.

2021-12-09 10:27 UTC, ivanruski approved these changes

2021-12-14 08:23 UTC, ivanruski requested changes
**issue:** If we make request with negative value for the `limit` param the api returns 503.

**suggestion:** We should add check in `handlers.go.extractRequestParams` that the `limit` param is non-negative value.

2021-12-16 08:10 UTC, ivanruski approved these changes

2021-12-16 08:16 UTC, merged